name: Testing stuff

on:
  push:
    branches:
      - partd

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: checking commits for
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          HAS_A_SKIP: ${{'has a skip'}}
        if: ${{contains(github.event.commits.*.message, 'skip') }}
        run: echo "$HAS_A_SKIP"
